db:
        host: 'localhost'
        port: 27017
        user: ''
        passwd: ''
        name: "packtrack-dev"
dev:
        debug: True
jwt:
        secret: 'keyboard cat'
        algorithm: 'HS256'
