app:
        secret: 'why not'
db:
        host: 'localhost'
        port: 27017
        user: ''
        passwd: ''
        name: "packtrack-dev"
dev:
        debug: True
jwt:
        secret: 'why not' 
        algorithm: 'HS256'
        access_expires: 15
        refresh_expires: 3
redis:
        host: 'localhost'
        port: 6379
        instances:
                revoke:
                        db: '0'
