app:
        secret: 'why not'
db:
        host: 'localhost'
        port: 27017
        user: ''
        passwd: ''
        name: "packtrack-dev"
dev:
        debug: True
jwt:
        secret: 'of course'
        algorithm: 'HS512'
        access_expires: 30 #minutes
        refresh_expires: 4 #days
redis:
        host: 'localhost'
        port: 6379
        instances:
                revoke:
                        db: '0'
